%% Generated by the Erlang ASN.1 compiler version:4.0.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ACP



-ifndef(_ACP_HRL_).
-define(_ACP_HRL_, true).

-record('AcpMessage',{
uri, callRef, body}).

-record('SDPEntry',{
name, value}).

-record('ThroughconnectType',{
localSDP = asn1_NOVALUE, remoteSDP = asn1_NOVALUE, mode}). % with extension mark

-record('ChangeMediaIRType',{
reason, sdp = asn1_NOVALUE}). % with extension mark

-record('ChangeMediaFailType',{
reason}). % with extension mark

-record('SignalType',{
signal, direction = asn1_DEFAULT}). % with extension mark

-record('ANYPACK',{
arg}).

-endif. %% _ACP_HRL_
