%% Generated by the Erlang ASN.1 compiler version:4.0.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module INCS3Internals



-ifndef(_INCS3INTERNALS_HRL_).
-define(_INCS3INTERNALS_HRL_, true).

-record('AddressEndType',{
callRef, digits = asn1_NOVALUE}).

-record('EventInformation',{
eventIndicator, eventPresentationIndicator}).

-record('CallDiversionInformation',{
notificationSubsOpts, redirectingReason}).

-record('CallProgressType',{
cause, causeInitiator, causeIsup = asn1_NOVALUE, eventInformation = asn1_NOVALUE, additionalInfo = asn1_NOVALUE, oBCI = asn1_NOVALUE, gNotification = asn1_NOVALUE, redirectionNumber = asn1_NOVALUE, redirectionRestInd = asn1_NOVALUE, callDiversionInfo = asn1_NOVALUE, facility = asn1_NOVALUE, sdp = asn1_NOVALUE, mediaPoint = asn1_NOVALUE, trunkGroupId = asn1_NOVALUE, callTransferNumber = asn1_NOVALUE, refer = asn1_NOVALUE, eventTime = asn1_NOVALUE}).

-record('FailureType',{
callRef, cause}).

-record('NetworkSRType',{
callRef}).

-record('ReleaseType',{
cause, causeInitiator, dialledDigits = asn1_NOVALUE, causeIsup = asn1_NOVALUE, additionalInfo = asn1_NOVALUE, trunkGroupId = asn1_NOVALUE, sid = asn1_NOVALUE, refer = asn1_NOVALUE, needAck, eventTime = asn1_NOVALUE}).

-record('ServiceFeatureType',{
cause, callRef = asn1_NOVALUE}).

-record('SetupCRType',{
connectedNumber = asn1_NOVALUE, additionalInfo, redirectionNumber = asn1_NOVALUE, redirectionRestInd = asn1_NOVALUE, sdp = asn1_NOVALUE, mediaPoint = asn1_NOVALUE, refer = asn1_NOVALUE, eventTime}).

-record('SDPType',{
type, body}).

-record('ReferType',{
exchange, routingKey = asn1_NOVALUE, sid = asn1_NOVALUE, callRef = asn1_NOVALUE, confId = asn1_NOVALUE}).

-record('SetupAckType',{
refer = asn1_NOVALUE, trunkGroupId = asn1_NOVALUE}).

-record('SetupIRType',{
domain, calledPartyNumber = asn1_NOVALUE, calledPartysCategory = asn1_NOVALUE, callingPartyNumber = asn1_NOVALUE, callingPartysCategory = asn1_NOVALUE, locationNumber = asn1_NOVALUE, originalCalledNumber = asn1_NOVALUE, userTeleserviceInformation = asn1_NOVALUE, genericNumber = asn1_NOVALUE, forwardCallIndicators = asn1_NOVALUE, redirectingNumber = asn1_NOVALUE, redirectingInformation = asn1_NOVALUE, uSIServiceIndicator = asn1_NOVALUE, uSIInformation = asn1_NOVALUE, isupCallRef = asn1_NOVALUE, sdp = asn1_NOVALUE, mediaPoint = asn1_NOVALUE, additionalInfo, trunkGroupId = asn1_NOVALUE, callingPartyInfo, calledPartyInfo, callingIfaceInfo, calledIfaceInfo, refer = asn1_NOVALUE, mode = asn1_NOVALUE, eventTime = asn1_NOVALUE}).

-record('CHUNT',{
'chunt-refer'}).

-record('SubsequentAddressType',{
callRef, digits}).

-record('UserDataType',{
callRef, uSIServiceIndicator, uSIInformation, infoDirection}).

-record('MGTSetTriggerTableArg_SEQOF',{
legID, serviceKey, eventTypeBCSM, monitorMode}).

-record('DPFacilityArg',{
legID, party}).

-record('DPArg',{
legID, bcsmEvent, party = asn1_NOVALUE, cgPN = asn1_NOVALUE, cdPN = asn1_NOVALUE, callingPartysCategory = asn1_NOVALUE, locationNumber = asn1_NOVALUE, originalCalledNumber = asn1_NOVALUE, userTeleserviceInformation = asn1_NOVALUE, genericNumber = asn1_NOVALUE, forwardCallIndicators = asn1_NOVALUE, redirectingNumber = asn1_NOVALUE, redirectingInformation = asn1_NOVALUE, uSIServiceIndicator = asn1_NOVALUE, uSIInformation = asn1_NOVALUE, digits = asn1_NOVALUE, cause = asn1_NOVALUE}).

-record('DPUTSIArg',{
legID, uSIServiceIndicator, uSIInformation, party}).

-record('OBCSMPars',{
startState, legID, cgPN = asn1_NOVALUE, routingInfo, routeList = asn1_NOVALUE, callingPartysCategory = asn1_NOVALUE, locationNumber = asn1_NOVALUE, originalCalledNumber = asn1_NOVALUE, userTeleserviceInformation = asn1_NOVALUE, genericNumber = asn1_NOVALUE, forwardCallIndicators = asn1_NOVALUE, redirectingNumber = asn1_NOVALUE, redirectingInformation = asn1_NOVALUE, uSIServiceIndicator = asn1_NOVALUE, uSIInformation = asn1_NOVALUE, setupTime = asn1_NOVALUE}).

-record('ChargingEventIndArg',{
callRef, eventTypeCharging}).

-record('PICArg',{
legID, pic, routingInfo, routeList = asn1_NOVALUE, callingPartyNumber = asn1_NOVALUE, callingPartysCategory = asn1_NOVALUE, locationNumber = asn1_NOVALUE, originalCalledNumber = asn1_NOVALUE, userTeleserviceInformation = asn1_NOVALUE, genericNumber = asn1_NOVALUE, forwardCallIndicators = asn1_NOVALUE, redirectingNumber = asn1_NOVALUE, redirectingInformation = asn1_NOVALUE, uSIServiceIndicator = asn1_NOVALUE, uSIInformation = asn1_NOVALUE, infoDirection = asn1_NOVALUE, party = asn1_NOVALUE, facilityGroup = asn1_NOVALUE, cause = asn1_NOVALUE}).

-record('EventTime',{
megaSec, sec, micSec}).

-define('emptyString', <<>>).
-define('oct0', <<0>>).
-define('oct1', <<1>>).
-define('oct2', <<2>>).
-define('oct3', <<3>>).
-define('oct4', <<4>>).
-define('oct5', <<5>>).
-define('oct6', <<6>>).
-define('oct7', <<7>>).
-define('oct8', <<8>>).
-define('oct9', <<9>>).
-define('octa', <<10>>).
-define('octb', <<11>>).
-endif. %% _INCS3INTERNALS_HRL_
