%% Generated by the Erlang ASN.1 compiler version:4.0.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module INCS3datatypes



-ifndef(_INCS3DATATYPES_HRL_).
-define(_INCS3DATATYPES_HRL_, true).

-record('ExportLegsType_SEQOF',{
sourceLeg, newLeg}).

-record('CollectedDigits',{
minimumNbOfDigits = asn1_DEFAULT, maximumNbOfDigits, endOfReplyDigit = asn1_NOVALUE, cancelDigit = asn1_NOVALUE, startDigit = asn1_NOVALUE, firstDigitTimeOut = asn1_NOVALUE, interDigitTimeOut = asn1_NOVALUE, errorTreatment, interruptableAnnInd = asn1_DEFAULT, voiceInformation = asn1_DEFAULT, voiceBack = asn1_DEFAULT, detectModem = asn1_DEFAULT}).

-record('InbandInfo',{
messageID, numberOfRepetitions = asn1_NOVALUE, duration = asn1_NOVALUE, interval = asn1_NOVALUE, preferredLanguage = asn1_NOVALUE}).

-record('InformationToRecord',{
messageID = asn1_NOVALUE, messageDeletionTimeOut = asn1_NOVALUE, timeToRecord = asn1_NOVALUE, controlDigits}).

-record('InformationToRecord_controlDigits',{
endOfRecordingDigit = asn1_NOVALUE, cancelDigit = asn1_NOVALUE, replayDigit = asn1_NOVALUE, restartRecordingDigit = asn1_NOVALUE, restartAllowed = asn1_DEFAULT, replayAllowed = asn1_DEFAULT}).

-record('MessageID_text',{
messageContent, attributes = asn1_NOVALUE}).

-record('MessageID_variableMessage',{
elementaryMessageID, variableParts}).

-record('SRFGapCriteria_iPAddressAndresource',{
iPAddressValue, gapOnResource}).

-record('Tone',{
toneID, duration = asn1_NOVALUE}).

-record('AdditionalCauseDescription',{
key = asn1_NOVALUE, value = asn1_NOVALUE}).

-record('SSNotification',{
family, cgpn, cdpn, servingSide, serviceTimeStamp, participants, internal, args}).

-record('MediaId',{
arg}).

-record('AdditionalISUP',{
message, params = asn1_NOVALUE}).

-record('AdditionalISUPParam',{
type, length, value}).

-record('AdditionalMegacoTransfer',{
callRef, legRef, remoteSDP}). % with extension mark

-record('AdditionalMegacoConference',{
callRef, legRef, remoteSDP}). % with extension mark

-record('BackwardServiceInteractionInd',{
conferenceTreatmentIndicator = asn1_NOVALUE, callCompletionTreatmentIndicator = asn1_NOVALUE}).

-record('BCSMEvent',{
eventTypeBCSM, monitorMode, legID = asn1_NOVALUE, dpSpecificCriteria = asn1_NOVALUE}).

-record('ChargingEvent',{
eventTypeCharging, monitorMode, legID = asn1_NOVALUE}).

-record('CollectInformation',{
numberingPlan = asn1_NOVALUE}). % with extension mark

-record('CollectNumberingPlan',{
name = asn1_NOVALUE, body = asn1_NOVALUE}). % with extension mark

-record('CounterAndValue',{
counterID, counterValue}).

-record('DefaultFaultHandling',{
action, treatment = asn1_NOVALUE}).

-record('DpSpecificCommonParameters',{
serviceAddressInformation, bearerCapability = asn1_NOVALUE, calledPartyNumber = asn1_NOVALUE, callingPartyNumber = asn1_NOVALUE, callingPartysCategory = asn1_NOVALUE, iPSSPCapabilities = asn1_NOVALUE, iPAvailable = asn1_NOVALUE, iSDNAccessRelatedInformation = asn1_NOVALUE, cGEncountered = asn1_NOVALUE, locationNumber = asn1_NOVALUE, serviceProfileIdentifier = asn1_NOVALUE, terminalType = asn1_NOVALUE, extensions = asn1_NOVALUE, chargeNumber = asn1_NOVALUE, servingAreaID = asn1_NOVALUE, serviceInteractionIndicators = asn1_NOVALUE, iNServiceCompatibilityIndication = asn1_NOVALUE, serviceInteractionIndicatorsTwo = asn1_NOVALUE, uSIServiceIndicator = asn1_NOVALUE, uSIInformation = asn1_NOVALUE, forwardGVNS = asn1_NOVALUE, createdCallSegmentAssociation = asn1_NOVALUE}).

-record('DpSpecificCriteria_numberOfDigitsTwo',{
requestedNumberOfDigits, minNumberOfDigits = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_collectedInfoSpecificInfo',{
calledPartynumber}).

-record('EventSpecificInformationBCSM_analysedInfoSpecificInfo',{
calledPartynumber}).

-record('EventSpecificInformationBCSM_routeSelectFailureSpecificInfo',{
failureCause = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_oCalledPartyBusySpecificInfo',{
busyCause = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_oNoAnswerSpecificInfo',{
}).

-record('EventSpecificInformationBCSM_oAnswerSpecificInfo',{
backwardGVNS = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_oMidCallSpecificInfo',{
connectTime = asn1_NOVALUE, oMidCallInfo = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_oDisconnectSpecificInfo',{
releaseCause = asn1_NOVALUE, connectTime = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_tBusySpecificInfo',{
busyCause = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_tNoAnswerSpecificInfo',{
}).

-record('EventSpecificInformationBCSM_tAnswerSpecificInfo',{
}).

-record('EventSpecificInformationBCSM_tMidCallSpecificInfo',{
connectTime = asn1_NOVALUE, tMidCallInfo = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_tDisconnectSpecificInfo',{
releaseCause = asn1_NOVALUE, connectTime = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_oTermSeizedSpecificInfo',{
}).

-record('EventSpecificInformationBCSM_oSuspend',{
}).

-record('EventSpecificInformationBCSM_tSuspend',{
}).

-record('EventSpecificInformationBCSM_origAttemptAuthorized',{
}).

-record('EventSpecificInformationBCSM_oReAnswer',{
}).

-record('EventSpecificInformationBCSM_tReAnswer',{
}).

-record('EventSpecificInformationBCSM_facilitySelectedAndAvailable',{
}).

-record('EventSpecificInformationBCSM_callAccepted',{
}).

-record('EventSpecificInformationBCSM_oAbandon',{
abandonCause = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_tAbandon',{
abandonCause = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_authorizeRouteFailure',{
authoriseRouteFailureCause = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_terminationAttemptAuthorized',{
}).

-record('EventSpecificInformationBCSM_orininationDenied',{
originationDeniedCause = asn1_NOVALUE}).

-record('EventSpecificInformationBCSM_terminationDenied',{
terminationDeniedCause = asn1_NOVALUE}).

-record('FilteredCallTreatment',{
sFBillingChargingCharacteristics, informationToSend = asn1_NOVALUE, maximumNumberOfCounters = asn1_NOVALUE, releaseCause = asn1_NOVALUE}).

-record('FilteringCriteria_addressAndService',{
calledAddressValue, serviceKey, callingAddressValue = asn1_NOVALUE, locationNumber = asn1_NOVALUE}).

-record('ForwardServiceInteractionInd',{
conferenceTreatmentIndicator = asn1_NOVALUE, callDiversionTreatmentIndicator = asn1_NOVALUE, callOfferingTreatmentIndicator = asn1_NOVALUE, callWaitingTreatmentIndicator = asn1_NOVALUE}).

-record('GapCriteria_calledAddressAndService',{
calledAddressValue, serviceKey}).

-record('GapCriteria_callingAddressAndService',{
callingAddressValue, serviceKey, locationNumber = asn1_NOVALUE}).

-record('GapOnService',{
serviceKey, dpCriteria = asn1_NOVALUE}).

-record('GapIndicators',{
duration, gapInterval}).

-record('GapTreatment_both',{
informationToSend, releaseCause}).

-record('INprofile',{
actionOnProfile, tDPIdentifier, dpName = asn1_NOVALUE, extensions = asn1_NOVALUE}).

-record('MidCallControlInfo_SEQOF',{
midCallInfoType, midCallReportType = asn1_DEFAULT}).

-record('MidCallInfo',{
iNServiceControlCode}).

-record('MidCallInfoType',{
iNServiceControlCodeLow, iNServiceControlCodeHigh = asn1_NOVALUE}).

-record('DTMiscCallInfo',{
messageType, dpAssignment = asn1_NOVALUE}).

-record('RequestedInformation',{
requestedInformationType, requestedInformationValue}).

-record('RequestedUTSI',{
uSIServiceIndicator, uSImonitorMode}).

-record('ServiceAddressInformation',{
serviceKey = asn1_NOVALUE, miscCallInfo, triggerType = asn1_NOVALUE}).

-record('ServiceInteractionIndicatorsTwo',{
forwardServiceInteractionInd = asn1_NOVALUE, backwardServiceInteractionInd = asn1_NOVALUE, bothwayThroughConnectionInd = asn1_NOVALUE, suspendTimer = asn1_NOVALUE, connectedNumberTreatmentInd = asn1_NOVALUE, suppressCallDiversionNotification = asn1_NOVALUE, suppressCallTransferNotification = asn1_NOVALUE, allowCdINNoPresentationInd = asn1_NOVALUE, userDialogueDurationInd = asn1_DEFAULT, overrideLineRestrictions = asn1_DEFAULT, suppressVPNAPP = asn1_DEFAULT, calledINNumberOverriding = asn1_NOVALUE, redirectServiceTreatmentInd = asn1_NOVALUE}).

-record('ServiceInteractionIndicatorsTwo_redirectServiceTreatmentInd',{
redirectReason = asn1_NOVALUE}).

-record('TraceItem',{
scf}).

-record('TriggerDataIdentifier',{
triggerID, profileIdentifier, extensions = asn1_NOVALUE}).

-record('TriggerResult',{
tDPIdentifer, actionPerformed, dpName = asn1_NOVALUE}).

-record('Trigger',{
tDPIdentifier, dpName = asn1_NOVALUE}).

-define('initialCallSegment', 1).
-define('dtleg1', <<1>>).
-define('dtleg2', <<2>>).
-define('highLayerCompatibilityLength', 2).
-define('minCauseLength', 1).
-define('numOfCounters', 100).
-define('numOfInfoItems', 5).
-define('minAChBillingChargingLength', 1).
-define('maxAChBillingChargingLength', 27).
-define('minATMTrafficDescriptorLength', 1).
-define('maxATMTrafficDescriptorLength', 27).
-define('minBackwardGVNSLength', 1).
-define('maxBackwardGVNSLength', 27).
-define('maxBearerCapabilityLength', 27).
-define('minBroadbandBearerCapabilityLength', 1).
-define('maxBroadbandBearerCapabilityLength', 27).
-define('minCalledDirectoryNumberLength', 1).
-define('maxCalledDirectoryNumberLength', 27).
-define('minCalledPartyNumberLength', 0).
-define('maxCalledPartyNumberLength', 15).
-define('minCalledPartySubaddressLength', 1).
-define('maxCalledPartySubaddressLength', 27).
-define('minCallingGeodeticLocationLength', 1).
-define('maxCallingGeodeticLocationLength', 10).
-define('minCallingPartyNumberLength', 1).
-define('maxCallingPartyNumberLength', 27).
-define('minCallingPartySubaddressLength', 1).
-define('maxCallingPartySubaddressLength', 27).
-define('minCallResultLength', 1).
-define('maxCallResultLength', 27).
-define('minCarrierLength', 3).
-define('maxCarrierLength', 10).
-define('maxCauseLength', 16).
-define('minDigitsLength', 1).
-define('maxDigitsLength', 27).
-define('minDisplayInformationLength', 1).
-define('maxDisplayInformationLength', 27).
-define('minEventSpecificInformationChargingLength', 1).
-define('maxEventSpecificInformationChargingLength', 27).
-define('minEventTypeChargingLength', 1).
-define('maxEventTypeChargingLength', 27).
-define('minFCIBillingChargingLength', 1).
-define('maxFCIBillingChargingLength', 27).
-define('minForwardGVNSLength', 1).
-define('maxForwardGVNSLength', 27).
-define('minGenericNameLength', 1).
-define('maxGenericNameLength', 27).
-define('minGenericNumberLength', 1).
-define('maxGenericNumberLength', 27).
-define('maxInitialTimeInterval', 27).
-define('maxINServiceCompatibilityIndLength', 27).
-define('minIPAvailableLength', 1).
-define('maxIPAvailableLength', 27).
-define('minIPSSPCapabilitiesLength', 1).
-define('maxIPSSPCapabilitiesLength', 27).
-define('minISDNAccessRelatedInfoLength', 1).
-define('maxISDNAccessRelatedInfoLength', 10).
-define('minISUPParameterLength', 1).
-define('maxISUPParameterLength', 255).
-define('maxISUPParameterType', 255).
-define('minLocationNumberLength', 1).
-define('maxLocationNumberLength', 27).
-define('minMidCallControlInfoNum', 1).
-define('maxMidCallControlInfoNum', 27).
-define('minOriginalCalledPartyIDLength', 1).
-define('maxOriginalCalledPartyIDLength', 15).
-define('minQoSParameterLength', 1).
-define('maxQoSParameterLength', 5).
-define('minReasonLength', 1).
-define('maxReasonLength', 5).
-define('minRedirectingPartyIDLength', 1).
-define('maxRedirectingPartyIDLength', 27).
-define('minRequestedUTSINum', 1).
-define('maxRequestedUTSINum', 27).
-define('minRouteListLength', 1).
-define('maxRouteListLength', 27).
-define('minRoutingNumberLength', 1).
-define('maxRoutingNumberLength', 27).
-define('minScfIDLength', 1).
-define('maxScfIDLength', 27).
-define('minSCIBillingChargingLength', 1).
-define('maxSCIBillingChargingLength', 27).
-define('minSDSSinformationLength', 1).
-define('maxSDSSinformationLength', 27).
-define('minServiceInteractionIndicatorsLength', 1).
-define('maxServiceInteractionIndicatorsLength', 5).
-define('minSFBillingChargingLength', 1).
-define('maxSFBillingChargingLength', 27).
-define('minUSIInformationLength', 1).
-define('maxUSIInformationLength', 5).
-define('minUSIServiceIndicatorLength', 1).
-define('maxUSIServiceIndicatorLength', 27).
-define('numOfBCSMEvents', 4).
-define('numOfBCUSMEvents', 4).
-define('numOfChargingEvents', 4).
-define('numOfCSAs', 10).
-define('numOfCSs', 10).
-define('numOfGenericNumbers', 2).
-define('numOfINProfile', 1).
-define('numOfTriggers', 27).
-define('numOfInServiceCompatibilityIndLength', 2).
-define('numOfLegs', 10).
-define('maxAmount', 10000).
-define('maxCallReferenceLength', 27).
-define('maxInitialUnitIncrement', 2).
-define('maxScalingFactor', 2).
-define('maxSegmentsPerDataInterval', 27).
-define('ub-nbCall', 27).
-define('numOfAddresses', 27).
-define('numOfServiceKeys', 3).
-define('minAttributesLength', 1).
-define('maxAttributesLength', 27).
-define('minMailBoxIDLength', 1).
-define('maxMailBoxIDLength', 27).
-define('minMessageContentLength', 1).
-define('maxMessageContentLength', 27).
-define('minReceivedInformationLength', 1).
-define('maxReceivedInformationLength', 27).
-define('maxRecordingTime', 27).
-define('numOfMessageIDs', 2).
-define('numOfExtensions', 1).
-define('maxRecordedMessageUnits', 27).
-endif. %% _INCS3DATATYPES_HRL_
