%%%-------------------------------------------------------------------
%%% -*- coding: utf-8 -*-
%%% @author Anton N Ryabkov <anton.ryabkov@gmail.com>
%%% @copyright (C) 2015, Eltex, Novosibirsk, Russia
%%% Created : 15. Дек. 2015 14:10
%%%-------------------------------------------------------------------

-define(ISUP_CAUSE_MATCH(Cause), ?ISUP_CAUSE_MATCH(_, _, Cause)).
-define(ISUP_CAUSE_MATCH(Location, Cause), ?ISUP_CAUSE_MATCH(_, Location, Cause)).
-define(ISUP_CAUSE_MATCH(CodingStandard, Location, Cause), <<1:1, CodingStandard:2, 0:1, Location:4, 1:1, Cause:7>>).

-define(ISUP_CAUSE(Cause), ?ISUP_CAUSE(?Q850_CS_ITU_T, ?Q850_LOCATION_U, Cause)).
-define(ISUP_CAUSE(Location, Cause), ?ISUP_CAUSE(?Q850_CS_ITU_T, Location, Cause)).
-define(ISUP_CAUSE(CodingStandard, Location, Cause), <<1:1, CodingStandard:2, 0:1, Location:4, 1:1, Cause:7>>).

%%--------------------------------------------------------------------
%% @doc Coding standards
%%--------------------------------------------------------------------
-define(Q850_CS_ITU_T, 2#00).
-define(Q850_CS_ISO_IEC, 2#01).
-define(Q850_CS_NATIONAL, 2#10).
-define(Q850_CS_LOCATION_IDENTIFIED, 2#11).
%%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

%%--------------------------------------------------------------------
%% @doc Location
%%--------------------------------------------------------------------
-define(Q850_LOCATION_U,    2#0000). % user
-define(Q850_LOCATION_LPN,  2#0001). % private network serving the local user
-define(Q850_LOCATION_LN,   2#0010). % public network serving the local user
-define(Q850_LOCATION_TN,   2#0011). % transit network
-define(Q850_LOCATION_RLN,  2#0100). % public network serving the remote user
-define(Q850_LOCATION_RPN,  2#0101). % private network serving the remote user
-define(Q850_LOCATION_INTL, 2#0111). % international network
-define(Q850_LOCATION_BI,   2#1010). % network beyond interworking point
-define(Q850_LOCATION_RES1, 2#1100). % reserved for national use
-define(Q850_LOCATION_RES2, 2#1101). % reserved for national use
-define(Q850_LOCATION_RES3, 2#1110). % reserved for national use
-define(Q850_LOCATION_RES4, 2#1111). % reserved for national use
%%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

%%--------------------------------------------------------------------
%% @doc ISUP Causes values
%%--------------------------------------------------------------------
-define(ISUP_CAUSE_1_UNALLOCATED_NUMBER, 1).
-define(ISUP_CAUSE_2_NO_ROUTE_TO_NETWORK, 2).
-define(ISUP_CAUSE_3_NO_ROUTE_TO_DESTINATION, 3).
-define(ISUP_CAUSE_4_SEND_SPECIAL_INFORMATION_TONE, 4).
-define(ISUP_CAUSE_5_MISDIALLED_TRUNK_PREFIX, 5).
-define(ISUP_CAUSE_6_CHANNEL_UNACCEPTABLE, 6).
-define(ISUP_CAUSE_7_CALL_AWARDED_AND_BEING_DELIVERED_IN_AN_ESTABLISHED_CHANNEL, 7).
-define(ISUP_CAUSE_8_PREEMPTION, 8).
-define(ISUP_CAUSE_9_PREEMPTION_CIRCUIT_RESERVED_FOR_REUSE, 9).
-define(ISUP_CAUSE_16_NORMAL_CALL_CLEARING, 16).
-define(ISUP_CAUSE_17_USER_BUSY, 17).
-define(ISUP_CAUSE_18_NO_USER_RESPONDING, 18).
-define(ISUP_CAUSE_19_NO_ANSWER_FROM_THE_USER, 19).
-define(ISUP_CAUSE_20_SUBSCRIBER_ABSENT, 20).
-define(ISUP_CAUSE_21_CALL_REJECTED, 21).
-define(ISUP_CAUSE_22_NUMBER_CHANGED, 22).
-define(ISUP_CAUSE_23_REDIRECTION_TO_NEW_DESTINATION, 23).
-define(ISUP_CAUSE_25_EXCHANGE_ROUTING_ERROR, 25).
-define(ISUP_CAUSE_26_NON_SELECTED_USER_CLEARING, 26).
-define(ISUP_CAUSE_27_DESTINATION_OUT_OF_ORDER, 27).
-define(ISUP_CAUSE_28_ADDRESS_INCOMPLETE, 28).
-define(ISUP_CAUSE_29_FACILITY_REJECTED, 29).
-define(ISUP_CAUSE_30_RESPONSE_TO_STATUS_ENQUIRY, 30).
-define(ISUP_CAUSE_31_NORMAL_UNSPECIFIED, 31).
-define(ISUP_CAUSE_34_NO_CIRCUIT_AVAILABLE, 34).
-define(ISUP_CAUSE_38_NETWORK_OUT_OF_ORDER, 38).
-define(ISUP_CAUSE_39_PERMANENT_FRAME_MODE_CONNECTION_OUT_OF_SERVICE, 39).
-define(ISUP_CAUSE_40_PERMANENT_FRAME_MODE_CONNECTION_OPERATIONAL, 40).
-define(ISUP_CAUSE_41_TEMPORARY_FAILURE, 41).
-define(ISUP_CAUSE_42_SWITCHING_EQUIPMENT_CONGESTION, 42).
-define(ISUP_CAUSE_43_ACCESS_INFORMATION_DISCARDED, 43).
-define(ISUP_CAUSE_44_REQUESTED_CIRCUIT_OR_CHANNEL_NOT_AVAILABLE, 44).
-define(ISUP_CAUSE_46_PRECEDENCE_CALL_BLOCKED, 46).
-define(ISUP_CAUSE_47_RESOURCE_UNAVAILABLE_UNSPECIFIED, 47).
-define(ISUP_CAUSE_49_QUALITY_OF_SERVICE_NOT_AVAILABLE, 49).
-define(ISUP_CAUSE_50_REQUESTED_FACILITY_NOT_SUBSCRIBED, 50).
-define(ISUP_CAUSE_53_OUTGOING_CALLS_BARRED_WITHIN_CUG, 53).
-define(ISUP_CAUSE_55_INCOMING_CALLS_BARRED_WITHIN_CUG, 55).
-define(ISUP_CAUSE_57_BEARER_CAPABILITY_NOT_AUTHORIZED, 57).
-define(ISUP_CAUSE_58_BEARER_CAPABILITY_NOT_PRESENTLY_AVAILABLE, 58).
-define(ISUP_CAUSE_62_INCONSISTENCY_IN_DESIGNATED_OUTGOING_ACCESS_INFORMATION_AND_SUBSCRIBER_CLASS, 62).
-define(ISUP_CAUSE_63_SERVICE_OR_OPTION_NOT_AVAILABLE_UNSPECIFIED, 63).
-define(ISUP_CAUSE_65_BEARER_CAPABILITY_NOT_IMPLEMENTED, 65).
-define(ISUP_CAUSE_66_CHANNEL_TYPE_NOT_IMPLEMENTED, 66).
-define(ISUP_CAUSE_69_REQUESTED_FACILITY_NOT_IMPLEMENTED, 69).
-define(ISUP_CAUSE_70_ONLY_RESTRICTED_DIGITAL_INFORMATION_BEARER_CAPABILITY_IS_AVAILABLE, 70).
-define(ISUP_CAUSE_79_SERVICE_OR_OPTION_NOT_IMPLEMENTED, 79).
-define(ISUP_CAUSE_81_INVALID_CALL_REFERENCE_VALUE, 81).
-define(ISUP_CAUSE_82_IDENTIFIED_CHANNEL_DOES_NOT_EXIST, 82).
-define(ISUP_CAUSE_83_A_SUSPENDED_CALL_EXISTS_BUT_THIS_CALL_IDENTITY_DOES_NOT, 83).
-define(ISUP_CAUSE_84_CALL_IDENTITY_IN_USE, 84).
-define(ISUP_CAUSE_85_NO_CALL_SUSPENDED, 85).
-define(ISUP_CAUSE_86_CALL_HAVING_THE_REQUESTED_CALL_IDENTITY_HAS_BEEN_CLEARED, 86).
-define(ISUP_CAUSE_87_USER_NOT_MEMBER_OF_CUG, 87).
-define(ISUP_CAUSE_88_INCOMPATIBLE_DESTINATION, 88).
-define(ISUP_CAUSE_90_NON_EXISTENT_CUG, 90).
-define(ISUP_CAUSE_91_INVALID_TRANSIT_NETWORK_SELECTION, 91).
-define(ISUP_CAUSE_95_INVALID_MESSAGE_UNSPECIFIED, 95).
-define(ISUP_CAUSE_96_MANDATORY_INFORMATION_ELEMENT_IS_MISSING, 96).
-define(ISUP_CAUSE_97_MESSAGE_TYPE_NON_EXISTENT_OR_NOT_IMPLEMENTED, 97).
-define(ISUP_CAUSE_98_MESSAGE_NOT_COMPATIBLE_WITH_CALL_STATE_OR_MESSAGE_TYPE_NON_EXISTENT, 98).
-define(ISUP_CAUSE_99_INFORMATION_ELEMENT_PARAMETER_NON_EXISTENT_OR_NOT_IMPLEMENTED, 99).
-define(ISUP_CAUSE_100_INVALID_INFORMATION_ELEMENT_CONTENTS, 100).
-define(ISUP_CAUSE_101_MESSAGE_NOT_COMPATIBLE_WITH_CALL_STATE, 101).
-define(ISUP_CAUSE_102_CALL_SETUP_TIME_OUT_FAILURE, 102).
-define(ISUP_CAUSE_103_PARAMETER_NON_EXISTENT_OR_NOT_IMPLEMENTED_PASSED_ON, 103).
-define(ISUP_CAUSE_110_MESSAGE_WITH_UNRECOGNIZED_PARAMETER_DISCARDED, 110).
-define(ISUP_CAUSE_111_PROTOCOL_ERROR_UNSPECIFIED, 111).
-define(ISUP_CAUSE_127_INTERNAL_ERROR_INTERWORKING_UNSPECIFIED, 127).
%%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++